export type ClientRow = {
  id: string
  name: string
  clientType: 'existing' | 'new'
  region: string
  tmsRevenue: number
  wave: '1' | '2' | '3'
  tcv: string
  tcvCurrency: string
  stage: string
  probability: string
  risk: string
  nextStep: string
  disqualifiedReason: string
  opportunityOwner: string
  salesCategory: string
}

export const clients: ClientRow[] = [
  { id: 'TBD', name: 'Virgin Money', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 27154967, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Happy to outsource more (no Genpact worries) and open to offshoring chat/ops, but voice offshoring is a firm no — and subscription pricing suits them.' },
  { id: 'TBD', name: 'Deutsche Bank (Hamburg)', clientType: 'existing', region: 'EMEA-HH', tmsRevenue: 17352102, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Fifth Third Bank', clientType: 'existing', region: 'NA', tmsRevenue: 14062039, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Open to outsourcing (sees the scalability/tech-gap logic) and fine digitizing front ends once proven — but low-cost-location offshoring is a legal/ops concern and voice is a firm no (back-office is fine), and pricing stays neutral with 5/3 covering the tech cost.' },
  { id: 'TBD', name: 'Metro Bank', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 12444434, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'UMB', clientType: 'existing', region: 'NA', tmsRevenue: 10320970, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Not rejected outright and open to aligning with the broader operating model rather than a UMB-specific solution — offshoring was the main focus, with voice confirmed to run from the Philippines and off-phone/back-office work from India.' },
  { id: 'TBD', name: 'Lloyds', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 9355708, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'UBS Financial Services Inc.', clientType: 'existing', region: 'NA', tmsRevenue: 8421652, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'PNC Bank', clientType: 'existing', region: 'NA', tmsRevenue: 5499455, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'ING (BV / Barneveld)', clientType: 'existing', region: 'EMEA-BV', tmsRevenue: 4690204, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Synovus Bank (incl. Business)', clientType: 'existing', region: 'NA', tmsRevenue: 3682762, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Centene Corporation', clientType: 'existing', region: 'NA', tmsRevenue: 3489339, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'HSBC Technology & Services (USA)', clientType: 'existing', region: 'NA', tmsRevenue: 3083942, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'First Hawaiian Bank', clientType: 'existing', region: 'NA', tmsRevenue: 2197457, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Arvest', clientType: 'existing', region: 'NA', tmsRevenue: 2036070, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'AIB', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 1827370, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Hancock-Whitney Bank', clientType: 'existing', region: 'NA', tmsRevenue: 1749293, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Simmons Bank', clientType: 'existing', region: 'NA', tmsRevenue: 1744800, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'First Bank Puerto Rico', clientType: 'existing', region: 'NA', tmsRevenue: 1721272, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Capital One', clientType: 'existing', region: 'NA', tmsRevenue: 1590370, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Degussa (Hamburg) / OLB (Oldemburgische Landesbank)', clientType: 'existing', region: 'EMEA-HH', tmsRevenue: 1533603, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'TDNA', clientType: 'existing', region: 'NA', tmsRevenue: 1461484, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Brim Financial', clientType: 'existing', region: 'NA', tmsRevenue: 1266978, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'US Bank (BV / Barneveld)', clientType: 'existing', region: 'EMEA-BV', tmsRevenue: 1151833, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Fairstone Bank of Canada', clientType: 'existing', region: 'NA', tmsRevenue: 978405, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Marlette Funding / Best Egg', clientType: 'existing', region: 'NA', tmsRevenue: 921463, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'M & T Bank', clientType: 'existing', region: 'NA', tmsRevenue: 910405, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Central Trust Bank', clientType: 'existing', region: 'NA', tmsRevenue: 909758, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'City National Bank', clientType: 'existing', region: 'NA', tmsRevenue: 793955, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Truist Bank', clientType: 'existing', region: 'NA', tmsRevenue: 717090, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Rogers Bank', clientType: 'existing', region: 'NA', tmsRevenue: 606000, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Jaja Finance', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 590000, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Regions Financial Corporation', clientType: 'existing', region: 'NA', tmsRevenue: 567870, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'ServisFirst', clientType: 'existing', region: 'NA', tmsRevenue: 555696, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: "President's Choice", clientType: 'existing', region: 'NA', tmsRevenue: 525550, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Santander Bank', clientType: 'existing', region: 'NA', tmsRevenue: 485904, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Royal Bank Of Canada', clientType: 'existing', region: 'NA', tmsRevenue: 477860, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Texas Capital', clientType: 'existing', region: 'NA', tmsRevenue: 426600, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Wells Fargo', clientType: 'existing', region: 'NA', tmsRevenue: 414000, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Marshall and Ilsley (BMO)', clientType: 'existing', region: 'NA', tmsRevenue: 380045, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Key Bank', clientType: 'existing', region: 'NA', tmsRevenue: 376815, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Union Bank (MUFG)', clientType: 'existing', region: 'NA', tmsRevenue: 344400, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Citizens Bank', clientType: 'existing', region: 'NA', tmsRevenue: 330550, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'BOKF, NA', clientType: 'existing', region: 'NA', tmsRevenue: 308614, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Bank Of America', clientType: 'existing', region: 'NA', tmsRevenue: 307350, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Banco Popular', clientType: 'existing', region: 'NA', tmsRevenue: 238800, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'The Bank Of Nova Scotia', clientType: 'existing', region: 'NA', tmsRevenue: 225000, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'IVR BOA', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 160907, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Navy Federal Credit Union', clientType: 'existing', region: 'NA', tmsRevenue: 151400, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Vancouver City Savings Credit', clientType: 'existing', region: 'NA', tmsRevenue: 132600, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Citibank', clientType: 'existing', region: 'NA', tmsRevenue: 106021, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'First Caribbean International Bank', clientType: 'existing', region: 'NA', tmsRevenue: 96000, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Bank of Montreal', clientType: 'existing', region: 'NA', tmsRevenue: 94334, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Valley National BK', clientType: 'existing', region: 'NA', tmsRevenue: 84000, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Ameriprise Trust Bank', clientType: 'existing', region: 'NA', tmsRevenue: 62220, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'NatWest', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 25243, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Reassured on IVR reliability and not opposed to a new provider given proper checks/approvals — though, as expected, Ailsa may see this as a chance to bring IVR back in-house and end the service; offshoring not applicable.' },
  { id: 'TBD', name: 'Empire Innovation Group', clientType: 'existing', region: 'NA', tmsRevenue: 25200, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'San Diego County Credit Union', clientType: 'existing', region: 'NA', tmsRevenue: 18780, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'MotivHealth', clientType: 'existing', region: 'NA', tmsRevenue: 10500, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Commerce Bank Of Kansas City', clientType: 'existing', region: 'NA', tmsRevenue: 7800, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Pitney Bowes Credit Corp', clientType: 'existing', region: 'NA', tmsRevenue: 7620, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Acclaris, Inc.', clientType: 'existing', region: 'NA', tmsRevenue: 5400, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Wright Express Financial Serv', clientType: 'existing', region: 'NA', tmsRevenue: 3120, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
  { id: 'TBD', name: 'Chase Corporate Card (JP Morgan)', clientType: 'existing', region: 'NA', tmsRevenue: 2400, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD' },
]

export function formatRevM(rev: number): string {
  if (rev === 0) return '$0'
  const m = rev / 1_000_000
  // >= $1M or >= $100K: 1 decimal place  e.g. $27.2M or $0.6M
  if (rev >= 100_000) return `$${m.toFixed(1)}M`
  // < $100K: 2 decimal places so small values retain precision  e.g. $0.01M
  return `$${m.toFixed(2)}M`
}
