export type ClientRow = {
  id: string
  name: string
  clientType: 'existing' | 'new'
  region: string
  tmsRevenue: number
  wave: '1' | '2' | '3'
  tcv: string
  tcvCurrency: string
  stage: string
  probability: string
  risk: string
  nextStep: string
  disqualifiedReason: string
  opportunityOwner: string
  salesCategory: string
  whisperDate: string
  pitchDate: string
  progressStatus: string
}

export const clients: ClientRow[] = [
  { id: 'TBD', name: 'Virgin Money', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 26229417, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Happy to outsource more (no Genpact worries) and open to offshoring chat/ops, but voice offshoring is a firm no — and subscription pricing suits them.', whisperDate: 'Jul 16, 2026', pitchDate: 'TBD', progressStatus: 'Alignment' },
  { id: 'TBD', name: 'Deutsche Bank (Hamburg)', clientType: 'existing', region: 'EMEA-HH', tmsRevenue: 16362300, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Fifth Third Bank', clientType: 'existing', region: 'NA', tmsRevenue: 13558253, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Open to outsourcing (sees the scalability/tech-gap logic) and fine digitizing front ends once proven — but low-cost-location offshoring is a legal/ops concern and voice is a firm no (back-office is fine), and pricing stays neutral with 5/3 covering the tech cost.', whisperDate: 'Jul 17, 2026', pitchDate: 'TBD', progressStatus: 'Alignment' },
  { id: 'TBD', name: 'Metro Bank', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 11793783, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'Aug 6, 2026', pitchDate: 'TBD', progressStatus: 'Alignment' },
  { id: 'UMB-1', name: 'UMB', clientType: 'existing', region: 'NA', tmsRevenue: 9913772, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Not rejected outright and open to aligning with the broader operating model rather than a UMB-specific solution — offshoring was the main focus, with voice confirmed to run from the Philippines and off-phone/back-office work from India.', whisperDate: 'Jul 20, 2026', pitchDate: 'Aug 31, 2026', progressStatus: 'Alignment' },
  { id: 'TBD', name: 'Lloyds', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 9103883, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'Aug 6, 2026', pitchDate: 'TBD', progressStatus: 'Alignment' },
  { id: 'TBD', name: 'UBS Financial Services Inc.', clientType: 'existing', region: 'NA', tmsRevenue: 8332814, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Alignment' },
  { id: 'TBD', name: 'PNC Bank', clientType: 'existing', region: 'NA', tmsRevenue: 5143978, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'ING (BV / Barneveld)', clientType: 'existing', region: 'EMEA-BV', tmsRevenue: 4502484, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Synovus Bank (incl. Business)', clientType: 'existing', region: 'NA', tmsRevenue: 3577829, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Centene Corporation', clientType: 'existing', region: 'NA', tmsRevenue: 3489339, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Alignment' },
  { id: 'TBD', name: 'HSBC Technology & Services (USA)', clientType: 'existing', region: 'NA', tmsRevenue: 2876755, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Alignment' },
  { id: 'TBD', name: 'First Hawaiian Bank', clientType: 'existing', region: 'NA', tmsRevenue: 1836975, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Arvest', clientType: 'existing', region: 'NA', tmsRevenue: 2022941, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'AIB', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 1827370, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '2', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Open to outsourcing despite no previous engagement with Genpact and no concerns expressed, welcomes potential enhanced technical capabilities. Customer Engagement team would be kept in place — no objections to offshore voice support — and AIB would be open to discuss a subscription-based pricing structure.', whisperDate: 'Jul 28, 2026', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Hancock-Whitney Bank', clientType: 'existing', region: 'NA', tmsRevenue: 1703235, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Simmons Bank', clientType: 'existing', region: 'NA', tmsRevenue: 1634077, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '2', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Open to outsourcing/offshoring from a business standpoint and not surprised by the request, but generally conservative on offshore support with legal team reaction flagged as a concern — questioned fallback options if agreement can\'t be reached, deferring specifics to the pitch.', whisperDate: 'Aug 5, 2026', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'First Bank Puerto Rico', clientType: 'existing', region: 'NA', tmsRevenue: 1610916, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Capital One', clientType: 'existing', region: 'NA', tmsRevenue: 1553245, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Degussa (Hamburg) / OLB (Oldemburgische Landesbank)', clientType: 'existing', region: 'EMEA-HH', tmsRevenue: 1374601, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'TDNA', clientType: 'existing', region: 'NA', tmsRevenue: 1461484, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Brim Financial', clientType: 'existing', region: 'NA', tmsRevenue: 1057228, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'US Bank (BV / Barneveld)', clientType: 'existing', region: 'EMEA-BV', tmsRevenue: 1151833, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Fairstone Bank of Canada', clientType: 'existing', region: 'NA', tmsRevenue: 978405, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Marlette Funding / Best Egg', clientType: 'existing', region: 'NA', tmsRevenue: 859588, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'M & T Bank', clientType: 'existing', region: 'NA', tmsRevenue: 337396, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Central Trust Bank', clientType: 'existing', region: 'NA', tmsRevenue: 864644, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'City National Bank', clientType: 'existing', region: 'NA', tmsRevenue: 732080, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Truist Bank', clientType: 'existing', region: 'NA', tmsRevenue: 717090, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Rogers Bank', clientType: 'existing', region: 'NA', tmsRevenue: 268907, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Jaja Finance', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 1444530, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Regions Financial Corporation', clientType: 'existing', region: 'NA', tmsRevenue: 567870, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'ServisFirst', clientType: 'existing', region: 'NA', tmsRevenue: 555696, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Mission Lane', clientType: 'existing', region: 'NA', tmsRevenue: 99655, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: "President's Choice", clientType: 'existing', region: 'NA', tmsRevenue: 469862, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '2', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Open to change and comfortable outsourcing more, but wants a real answer on why price wouldn\'t drop if offshoring cuts costs and tech doesn\'t visibly improve outbound fraud — and Ray will want the fraud team in future conversations.', whisperDate: 'Jul 31, 2026', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Santander Bank', clientType: 'existing', region: 'NA', tmsRevenue: 485904, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Royal Bank Of Canada', clientType: 'existing', region: 'NA', tmsRevenue: 477860, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Texas Capital', clientType: 'existing', region: 'NA', tmsRevenue: 364725, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '3', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Alignment' },
  { id: 'TBD', name: 'Wells Fargo', clientType: 'existing', region: 'NA', tmsRevenue: 414000, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Marshall and Ilsley (BMO)', clientType: 'existing', region: 'NA', tmsRevenue: 380045, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Key Bank', clientType: 'existing', region: 'NA', tmsRevenue: 376815, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Union Bank (MUFG)', clientType: 'existing', region: 'NA', tmsRevenue: 331182, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Citizens Bank', clientType: 'existing', region: 'NA', tmsRevenue: 330550, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'BOKF, NA', clientType: 'existing', region: 'NA', tmsRevenue: 265301, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Bank Of America', clientType: 'existing', region: 'NA', tmsRevenue: 307350, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Banco Popular', clientType: 'existing', region: 'NA', tmsRevenue: 238800, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'The Bank Of Nova Scotia', clientType: 'existing', region: 'NA', tmsRevenue: 225000, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'IVR BOA', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 160907, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Navy Federal Credit Union', clientType: 'existing', region: 'NA', tmsRevenue: 151400, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Vancouver City Savings Credit', clientType: 'existing', region: 'NA', tmsRevenue: 132600, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Citibank', clientType: 'existing', region: 'NA', tmsRevenue: 106021, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'First Caribbean International Bank', clientType: 'existing', region: 'NA', tmsRevenue: 96000, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Bank of Montreal', clientType: 'existing', region: 'NA', tmsRevenue: 94334, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Valley National BK', clientType: 'existing', region: 'NA', tmsRevenue: 81938, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Ameriprise Trust Bank', clientType: 'existing', region: 'NA', tmsRevenue: 62220, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'NatWest', clientType: 'existing', region: 'EMEA-UK', tmsRevenue: 25243, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '2', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'Reassured on IVR reliability and not opposed to a new provider given proper checks/approvals — though, as expected, Ailsa may see this as a chance to bring IVR back in-house and end the service; offshoring not applicable.', whisperDate: 'Jul 20, 2026', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Empire Innovation Group', clientType: 'existing', region: 'NA', tmsRevenue: 25200, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'San Diego County Credit Union', clientType: 'existing', region: 'NA', tmsRevenue: 18780, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'MotivHealth', clientType: 'existing', region: 'NA', tmsRevenue: 10500, wave: '1', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Commerce Bank Of Kansas City', clientType: 'existing', region: 'NA', tmsRevenue: 7800, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Pitney Bowes Credit Corp', clientType: 'existing', region: 'NA', tmsRevenue: 7620, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Acclaris, Inc.', clientType: 'existing', region: 'NA', tmsRevenue: 5400, wave: '3', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Wright Express Financial Serv', clientType: 'existing', region: 'NA', tmsRevenue: 3120, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
  { id: 'TBD', name: 'Chase Corporate Card (JP Morgan)', clientType: 'existing', region: 'NA', tmsRevenue: 2400, wave: '2', tcv: 'TBD', tcvCurrency: 'TBD', stage: '1', probability: 'TBD', risk: 'TBD', nextStep: 'TBD', disqualifiedReason: 'TBD', opportunityOwner: 'TBD', salesCategory: 'TBD', whisperDate: 'TBD', pitchDate: 'TBD', progressStatus: 'Exploration' },
]

export function formatRevM(rev: number): string {
  if (rev === 0) return '$0'
  const m = rev / 1_000_000
  // >= $100K: 1 decimal place  e.g. $26.2M or $0.6M
  if (rev >= 100_000) return `$${m.toFixed(1)}M`
  // $10K–$100K: 2 decimals so small values retain precision  e.g. $0.03M
  if (rev >= 10_000) return `$${m.toFixed(2)}M`
  // < $10K: 3 decimals so the smallest values remain legible  e.g. $0.008M
  return `$${m.toFixed(3)}M`
}
